export const CAPTURE_DATE = '2026-07-27';

export type ScreenshotRole = 'guest' | 'attendee' | 'organizer';
export type ScreenshotViewportName = 'mobile-390x844' | 'desktop-1440x900';

export interface ScreenshotCapture {
  readonly id: string;
  readonly tier: 1 | 2 | 3;
  readonly page: string;
  readonly state: string;
  readonly route: string;
  readonly role: ScreenshotRole;
  readonly data: string;
  readonly version: `v${number}`;
  readonly viewportName: ScreenshotViewportName;
  readonly viewport: Readonly<{ width: number; height: number }>;
  readonly fixedTime?: string;
  readonly folder: readonly string[];
  readonly readyText: string;
  readonly visibleTexts: readonly string[];
  readonly visibleLabels?: readonly string[];
  readonly scrollToText?: string;
  readonly purpose: string;
  readonly reviewFocus: string;
}

/**
 * Captures are added one at a time after the previous state is proven stable.
 */
export const SCREENSHOT_CAPTURES: readonly ScreenshotCapture[] = [
  {
    id: 'browse-ready-desktop',
    tier: 1,
    page: 'browse',
    state: 'ready',
    route: '/events',
    role: 'guest',
    data: 'seedA',
    version: 'v01',
    viewportName: 'desktop-1440x900',
    viewport: { width: 1440, height: 900 },
    folder: ['01-tier-1-core-flow', 'browse'],
    readyText: 'Explore Experiences',
    visibleTexts: ['Midnight Frequency', 'Builders on Stellar'],
    purpose: 'Represents the public discovery surface with a populated event grid.',
    reviewFocus: 'Review page hierarchy, event-card consistency, navigation, filter density, and desktop spacing.',
  },
  {
    id: 'event-detail-ready-mobile',
    tier: 1,
    page: 'event-detail',
    state: 'ready',
    route: '/events/event-seed-a-01',
    role: 'guest',
    data: 'seedA',
    version: 'v01',
    viewportName: 'mobile-390x844',
    viewport: { width: 390, height: 844 },
    folder: ['01-tier-1-core-flow', 'event-detail'],
    readyText: 'Midnight Frequency',
    visibleTexts: ['On sale', 'The Foundry', '18.00', 'Buy 1 ticket'],
    visibleLabels: ['Go back'],
    purpose: 'Represents the public mobile event-detail surface when an event is available for purchase.',
    reviewFocus: 'Review event-information hierarchy; date, venue, price and availability readability; purchase CTA placement and visibility; mobile header and back navigation; clipping, overflow, and hidden content.',
  },
  {
    id: 'purchase-review-ready-mobile',
    tier: 1,
    page: 'purchase',
    state: 'review-ready',
    route: '/events/event-seed-a-01/checkout',
    role: 'attendee',
    data: 'seedA',
    version: 'v01',
    viewportName: 'mobile-390x844',
    viewport: { width: 390, height: 844 },
    folder: ['01-tier-1-core-flow', 'purchase'],
    readyText: 'Buy 1 ticket',
    visibleTexts: [
      'Midnight Frequency',
      '1 × General Admission ticket',
      'Estimated network fee',
      'Total required',
      'Available balance',
      'Estimated remaining',
      'Confirm and pay 18.01 XLM',
    ],
    visibleLabels: ['Go back'],
    scrollToText: 'Confirm and pay 18.01 XLM',
    purpose: 'Represents the authenticated mobile checkout review after the ticket price, simulated fee, balance, and policies are ready for confirmation.',
    reviewFocus: 'Review purchase-summary hierarchy, fee and total clarity, balance and remaining-funds readability, policy comprehension, confirmation CTA prominence, mobile spacing, and clipping or overflow.',
  },
  {
    id: 'purchase-receipt-confirmed-mobile',
    tier: 1,
    page: 'purchase-receipt',
    state: 'confirmed',
    route: '/purchases/00000000-0000-4000-8000-000000000401',
    role: 'attendee',
    data: 'seedA',
    version: 'v01',
    viewportName: 'mobile-390x844',
    viewport: { width: 390, height: 844 },
    folder: ['01-tier-1-core-flow', 'purchase-receipt'],
    readyText: 'Your ticket is confirmed',
    visibleTexts: [
      'Purchase receipt',
      'Midnight Frequency',
      '1 × General Admission',
      'Amount paid',
      '18.00 XLM',
      'Network fee',
      '0.01 XLM',
      'Available in My Tickets',
      'View ticket',
      'View transaction',
    ],
    purpose: 'Represents the authenticated mobile receipt after a primary ticket purchase is confirmed and synchronized into My Tickets.',
    reviewFocus: 'Review confirmation hierarchy, event identity, amount and fee clarity, receipt-fact scanning, transaction provenance, next-action prominence, mobile navigation, and clipping or overflow.',
  },

  {
    id: 'my-tickets-upcoming-mobile',
    tier: 1,
    page: 'my-tickets',
    state: 'upcoming',
    route: '/tickets',
    role: 'attendee',
    data: 'seedA',
    version: 'v01',
    viewportName: 'mobile-390x844',
    viewport: { width: 390, height: 844 },
    folder: ['01-tier-1-core-flow', 'my-tickets'],
    readyText: 'My Tickets',
    visibleTexts: [
      'UPCOMING',
      'GENERAL ADMISSION',
      'Midnight Frequency',
      'The Foundry',
      'VIEW TICKET',
      'VIEW RECEIPT',
      'SHOW QR',
      'LIST FOR SALE',
    ],
    scrollToText: 'VIEW TICKET',
    purpose: 'Represents the authenticated mobile My Tickets surface with a synchronized upcoming ticket ready for viewing, receipt access, QR entry, or resale.',
    reviewFocus: 'Review upcoming-tab clarity, ticket-card hierarchy, event date and venue readability, ticket identity treatment, primary and secondary action priority, mobile navigation, spacing, clipping, and overflow.',
  },

  {
    id: 'scanner-ready-mobile',
    tier: 1,
    page: 'scanner',
    state: 'ready',
    route: '/organizer/events/event-seed-a-01/check-in',
    role: 'organizer',
    data: 'seedA',
    version: 'v01',
    viewportName: 'mobile-390x844',
    viewport: { width: 390, height: 844 },
    fixedTime: '2026-09-12T18:15:00+05:30',
    folder: ['01-tier-1-core-flow', 'scanner'],
    readyText: 'Door Status',
    visibleTexts: [
      'Midnight Frequency',
      'Ready for check-in',
      'Door Status',
      'Sold',
      '214',
      'Checked in',
      '37',
      'Remaining',
      '177',
      'Organizer Wallet',
      'Connected:',
      'Scanner',
      'Enable camera',
    ],
    visibleLabels: ['Go back'],
    scrollToText: 'Enable camera',
    purpose: 'Represents the authenticated organizer mobile check-in surface after ownership, authoritative event status, the door window, and the matching wallet are confirmed, before camera activation.',
    reviewFocus: 'Review ready-for-check-in status, door statistics, organizer-wallet confirmation, camera CTA prominence, mobile panel stacking, spacing, clipping, and overflow.',
  },

  {
    id: 'organizer-event-draft-ready-desktop',
    tier: 1,
    page: 'organizer-event-draft',
    state: 'ready',
    route: '/organizer/drafts/draft-seed-a-07',
    role: 'organizer',
    data: 'seedA',
    version: 'v01',
    viewportName: 'desktop-1440x900',
    viewport: { width: 1440, height: 900 },
    folder: ['01-tier-1-core-flow', 'organizer-event-draft'],
    readyText: 'Midnight Frequency',
    visibleTexts: [
      'Private event workspace',
      'Revision 4 · Saved',
      'Public event information',
      'Delete draft',
      'Save draft',
    ],
    visibleLabels: [
      'Event name',
      'Short summary',
      'Full description',
      'Poster URL',
      'Category',
    ],
    purpose: 'Represents a signed-in organizer reopening a populated, saved event draft in its stable editable workspace.',
    reviewFocus: 'Review draft hierarchy, saved-state clarity, edit and delete action prominence, form grouping, field density, desktop spacing, back navigation, and clipping or overflow.',
  },

  {
    id: 'organizer-event-ready-desktop',
    tier: 1,
    page: 'organizer-event',
    state: 'ready',
    route: '/organizer/events/event-seed-a-01',
    role: 'organizer',
    data: 'seedA',
    version: 'v01',
    viewportName: 'desktop-1440x900',
    viewport: { width: 1440, height: 900 },
    folder: ['01-tier-1-core-flow', 'organizer-event'],
    readyText: 'Midnight Frequency',
    visibleTexts: [
      'Confirmed from Stellar',
      'Tickets sold',
      'Sell-through',
      'Gross primary sales',
      'Held in escrow',
      'Organizer tools',
      'Open scanner',
      'Lifecycle actions',
      'Review cancellation',
    ],
    purpose: 'Represents the authenticated organizer desktop management surface for a published event with confirmed Stellar state.',
    reviewFocus: 'Review lifecycle and authority hierarchy, sales and escrow metrics, locked-versus-editable information, scanner access, lifecycle controls, activity visibility, desktop density, clipping, and overflow.',
  },
  {
    id: 'marketplace-listings-loaded-desktop',
    tier: 2,
    page: 'marketplace',
    state: 'listings-loaded',
    route: '/marketplace',
    role: 'guest',
    data: 'seedA',
    version: 'v01',
    viewportName: 'desktop-1440x900',
    viewport: { width: 1440, height: 900 },
    folder: ['02-tier-2-support-flow', 'marketplace'],
    readyText: 'Ticket Marketplace',
    visibleTexts: [
      'Active Listings',
      'Royalties Enforced',
      'On-chain',
      'Midnight Frequency',
      'Builders on Stellar',
      'Indie After Dark',
      'Buy Now',
    ],
    purpose: 'Represents the public desktop secondary marketplace with multiple open resale listings.',
    reviewFocus: 'Review marketplace hierarchy, trust indicators, resale-card consistency, seller and ask-price readability, purchase CTA prominence, desktop density, clipping, and overflow.',
  },
  {
    id: 'ticket-detail-ready-mobile',
    tier: 2,
    page: 'ticket-detail',
    state: 'ready',
    route: '/tickets/ticket-seed-a-01',
    role: 'attendee',
    data: 'seedA',
    version: 'v01',
    viewportName: 'mobile-390x844',
    viewport: { width: 390, height: 844 },
    folder: ['02-tier-2-support-flow', 'ticket-detail'],
    readyText: 'Midnight Frequency',
    visibleTexts: [
      'Active · General Admission',
      'Ticket ID',
      'ticket-seed-a-01',
      'Show QR',
      'View receipt',
    ],
    purpose: 'Represents an authenticated attendee mobile ticket detail with current ownership and its primary actions available.',
    reviewFocus: 'Review ticket identity hierarchy, event date and venue readability, ownership-state language, QR and receipt action prominence, mobile back navigation, clipping, and overflow.',
  },
  {
    id: 'qr-display-active-mobile',
    tier: 2,
    page: 'qr-display',
    state: 'active',
    route: '/tickets/ticket-seed-a-01/qr',
    role: 'attendee',
    data: 'seedA',
    version: 'v01',
    viewportName: 'mobile-390x844',
    viewport: { width: 390, height: 844 },
    folder: ['02-tier-2-support-flow', 'qr-display'],
    readyText: 'Your ticket',
    visibleTexts: [
      'ticket-seed-a-01',
      'Refreshes in',
      'Refresh and revalidate',
    ],
    visibleLabels: ['Active entry QR'],
    purpose: 'Represents the authenticated attendee mobile entry screen with an active rotating ticket QR.',
    reviewFocus: 'Review QR dominance and scanability, ticket identity, countdown and refresh affordance, wallet-address treatment, mobile spacing, warning-strip clearance, clipping, and overflow.',
  },
  {
    id: 'organizer-dashboard-populated-desktop',
    tier: 2,
    page: 'organizer-dashboard',
    state: 'populated',
    route: '/organizer/events',
    role: 'organizer',
    data: 'seedA',
    version: 'v01',
    viewportName: 'desktop-1440x900',
    viewport: { width: 1440, height: 900 },
    folder: ['02-tier-2-support-flow', 'organizer-dashboard'],
    readyText: 'Organizer Hub',
    visibleTexts: [
      'Private drafts',
      'Published events',
      'Indie After Dark',
      'Midnight Frequency',
      'Manage Event',
      'Create event',
    ],
    purpose: 'Represents the populated organizer dashboard where organizers can find drafts, published events, and management actions.',
    reviewFocus: 'Review information hierarchy, draft and published-event separation, metrics, recency and status readability, Manage Event prominence, desktop density, navigation, clipping, and overflow.',
  },

  {
    id: 'auth-default-mobile',
    tier: 3,
    page: 'auth',
    state: 'default',
    route: '/auth',
    role: 'guest',
    data: 'seedA',
    version: 'v01',
    viewportName: 'mobile-390x844',
    viewport: { width: 390, height: 844 },
    folder: ['03-tier-3-edge-flow', 'auth'],
    readyText: 'Sign in',
    visibleTexts: [
      'Continue with Google or a six-digit email code.',
      'Continue with Google',
      'Send email code',
    ],
    purpose: 'Represents the default mobile onboarding surface for signing in through Google or email OTP.',
    reviewFocus: 'Review sign-in hierarchy, provider choice clarity, email-field usability, CTA prominence, mobile spacing, keyboard-safe layout, header treatment, disclosure placement, clipping, and overflow.',
  },

  {
    id: 'create-event-preparing-desktop',
    tier: 3,
    page: 'create-event',
    state: 'preparing',
    route: '/organizer/events/new',
    role: 'organizer',
    data: 'seedA',
    version: 'v01',
    viewportName: 'desktop-1440x900',
    viewport: { width: 1440, height: 900 },
    folder: ['03-tier-3-edge-flow', 'create-event'],
    readyText: 'Preparing your private draft…',
    visibleTexts: [
      'A stable event ID is reserved now.',
      'Nothing is published or submitted to Stellar.',
    ],
    purpose: 'Represents the organizer transition while a private draft and stable future event ID are being prepared.',
    reviewFocus: 'Review loading-state hierarchy, truthful explanation of what is and is not happening, header and back navigation, desktop centering, excessive empty space, clipping, and false-success cues.',
  },

  {
    id: 'not-found-default-desktop',
    tier: 3,
    page: 'not-found',
    state: 'default',
    route: '/not-found/screenshot-seed-a',
    role: 'guest',
    data: 'seedA',
    version: 'v01',
    viewportName: 'desktop-1440x900',
    viewport: { width: 1440, height: 900 },
    folder: ['03-tier-3-edge-flow', 'not-found'],
    readyText: 'Page not found',
    visibleTexts: [
      'StellarTickets',
      'Discover',
      'Marketplace',
      'My Tickets',
      'Account',
    ],
    purpose: 'Represents the default application response for an unknown durable route.',
    reviewFocus: 'Review 404 hierarchy, recovery through persistent navigation, empty-space balance, testnet disclosure, desktop alignment, clipping, and whether the page gives sufficient next direction.',
  },

];
